name: Pull request
on:
  pull_request:
jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - run: echo pull_request
      - uses: actions/checkout@v2
      - run: gh pr merge --merge ${{ github.event.pull_request.number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}